// dashboardActionTypes.js

export const FETCH_FIRST_CARDS_REQUEST = 'FETCH_FIRST_CARDS_REQUEST';
export const FETCH_FIRST_CARDS_SUCCESS = 'FETCH_FIRST_CARDS_SUCCESS';
export const FETCH_FIRST_CARDS_FAILURE = 'FETCH_FIRST_CARDS_FAILURE';

export const FETCH_GRAPH_REQUEST = 'FETCH_GRAPH_REQUEST';
export const FETCH_GRAPH_SUCCESS = 'FETCH_GRAPH_SUCCESS';
export const FETCH_GRAPH_FAILURE = 'FETCH_GRAPH_FAILURE';
